export const employeeConstants = {
  
  
  EMPLOYEE_INSERT_SUCCESS: "EMPLOYEE_INSERT_SUCCESS",
  EMPLOYEE_GET_SUCCESS: "EMPLOYEE_GET_SUCCESS",
  EMPLOYEE_DELETE_SUCCESS:"EMPLOYEE_DELETE_SUCCESS",
  EMPLOYEE_UPDATE_SUCCESS:"EMPLOYEE_UPDATE_SUCCESS"
  
};


